# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
 
  config.vm.box = "box-cutter/ubuntu1404"
  config.vm.network "public_network", bridge: "Intel(R) 82579LM Gigabit Network Connection", ip: "192.168.100.200",
	use_dhcp_assigned_default_route: true  
  config.vm.hostname = "devstack-control"


  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  
     # Customize the amount of memory on the VM:
     vb.memory = "4096"
  end
  
 config.vm.provision "shell", path: "bootstrap.sh", privileged: false

  
end